"""
This type stub file was generated by pyright.
"""

from ldap import __version__
from ldap.schema.subentry import SCHEMA_ATTRS, SCHEMA_ATTR_MAPPING, SCHEMA_CLASS_MAPPING, SubSchema, urlfetch
from ldap.schema.models import *

"""
ldap.schema -  LDAPv3 schema handling

See https://www.python-ldap.org/ for details.
"""
