"""
This type stub file was generated by pyright.
"""

"""
ldap.schema.tokenizer - Low-level parsing functions for schema element strings

See https://www.python-ldap.org/ for details.
"""
TOKENS_FINDALL = ...
UNESCAPE_PATTERN = ...
def split_tokens(s): # -> list[Any]:
   """
    Returns list of syntax elements with quotes and spaces stripped.
    """
   ...

def extract_tokens(l, known_tokens): # -> dict[Any, Any]:
   """
  Returns dictionary of known tokens with all values
  """
   ...

