"""
This type stub file was generated by pyright.
"""

from ldap.extop import ExtendedResponse
from pyasn1.type import univ

"""
ldap.extop.passwd - Classes for Password Modify extended operation
(see RFC 3062)

See https://www.python-ldap.org/ for details.
"""
class PasswordModifyResponse(ExtendedResponse):
    responseName = ...
    class PasswordModifyResponseValue(univ.Sequence):
        componentType = ...
    
    
    def decodeResponseValue(self, value): # -> bytes:
        ...
    


