"""
This type stub file was generated by pyright.
"""

from collections import UserDict

"""Compatibility wrappers for Py2/Py3."""
IterableUserDict = UserDict
def reraise(exc_type, exc_value, exc_traceback):
    """Re-raise an exception given information from sys.exc_info()

    Note that unlike six.reraise, this does not support replacing the
    traceback. All arguments must come from a single sys.exc_info() call.
    """
    ...

