"""
This type stub file was generated by pyright.
"""

"""
filters.py - misc stuff for handling LDAP filter strings (see RFC2254)

See https://www.python-ldap.org/ for details.

Compatibility:
- Tested with Python 2.0+
"""
def escape_filter_chars(assertion_value, escape_mode=...): # -> LiteralString:
   """
  Replace all special characters found in assertion_value
  by quoted notation.

  escape_mode
      If 0 only special chars mentioned in RFC 4515 are escaped.
      If 1 all NON-ASCII chars are escaped.
      If 2 all chars are escaped.
  """
   ...

def filter_format(filter_template, assertion_values):
   """
  filter_template
        String containing %s as placeholder for assertion values.
  assertion_values
        List or tuple of assertion values. Length must match
        count of %s in filter_template.
  """
   ...

def time_span_filter(filterstr=..., from_timestamp=..., until_timestamp=..., delta_attr=...): # -> str:
   """
    If last_run_timestr is non-zero filterstr will be extended
    """
   ...

