"""
This type stub file was generated by pyright.
"""

"""
Helper class for using logging as trace file object
"""
class logging_file_class:
    def __init__(self, logging_level) -> None:
        ...
    
    def write(self, msg): # -> None:
        ...
    
    def flush(self): # -> None:
        ...
    


logging_file_obj = ...
