"""
This type stub file was generated by pyright.
"""

"""
ldap.modlist - create add/modify modlist's

See https://www.python-ldap.org/ for details.
"""
def addModlist(entry, ignore_attr_types=...): # -> list[Any]:
  """Build modify list for call of method LDAPObject.add()"""
  ...

def modifyModlist(old_entry, new_entry, ignore_attr_types=..., ignore_oldexistent=..., case_ignore_attr_types=...): # -> list[Any]:
  """
  Build differential modify list for calling LDAPObject.modify()/modify_s()

  old_entry
      Dictionary holding the old entry
  new_entry
      Dictionary holding what the new entry should be
  ignore_attr_types
      List of attribute type names to be ignored completely
  ignore_oldexistent
      If non-zero attribute type names which are in old_entry
      but are not found in new_entry at all are not deleted.
      This is handy for situations where your application
      sets attribute value to '' for deleting an attribute.
      In most cases leave zero.
  case_ignore_attr_types
      List of attribute type names for which comparison will be made
      case-insensitive
  """
  ...

