"""
This type stub file was generated by pyright.
"""

"""
ldap.resiter - processing LDAP results with iterators

See https://www.python-ldap.org/ for details.
"""
class ResultProcessor:
    """
    Mix-in class used with ldap.ldapopbject.LDAPObject or derived classes.
    """
    def allresults(self, msgid, timeout=..., add_ctrls=...): # -> Generator[tuple[Any, Any, Any, Any], Any, None]:
        """
        Generator function which returns an iterator for processing all LDAP operation
        results of the given msgid like retrieved with LDAPObject.result3() -> 4-tuple
        """
        ...
    


