"""
This type stub file was generated by pyright.
"""

import logging

_ctx = ...
LOGGER_KEY = ...
DEFAULT_LEVEL = ...
PY2 = ...
if PY2:
    text_type = ...
else:
    text_type = ...
class ColorFormatter(logging.Formatter):
    def __init__(self, style_kwargs) -> None:
        ...
    
    def format(self, record): # -> str:
        ...
    


class ClickHandler(logging.Handler):
    def __init__(self, echo_kwargs) -> None:
        ...
    
    def emit(self, record): # -> None:
        ...
    


def basic_config(logger=..., style_kwargs=..., echo_kwargs=...): # -> Logger:
    '''Set up the default handler (:py:class:`ClickHandler`) and formatter
    (:py:class:`ColorFormatter`) on the given logger.'''
    ...

