"""
This type stub file was generated by pyright.
"""

from ldap.controls import LDAPControl, RequestControl

"""
controls.libldap - LDAP controls wrapper classes with en-/decoding done
by OpenLDAP functions

See https://www.python-ldap.org/ for details.
"""
class AssertionControl(RequestControl):
  """
  LDAP Assertion control, as defined in RFC 4528

  filterstr
    LDAP filter string specifying which assertions have to match
    so that the server processes the operation
  """
  controlType = ...
  def __init__(self, criticality=..., filterstr=...) -> None:
    ...
  
  def encodeControlValue(self):
    ...
  


class MatchedValuesControl(RequestControl):
  """
  LDAP Matched Values control, as defined in RFC 3876

  filterstr
    LDAP filter string specifying which attribute values
    should be returned
  """
  controlType = ...
  def __init__(self, criticality=..., filterstr=...) -> None:
    ...
  
  def encodeControlValue(self):
    ...
  


class SimplePagedResultsControl(LDAPControl):
  """
  LDAP Control Extension for Simple Paged Results Manipulation

  size
    Page size requested (number of entries to be returned)
  cookie
    Cookie string received with last page
  """
  controlType = ...
  def __init__(self, criticality=..., size=..., cookie=...) -> None:
    ...
  
  def encodeControlValue(self):
    ...
  
  def decodeControlValue(self, encodedControlValue): # -> None:
    ...
  


